# Generated by Django 4.2.5 on 2023-09-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(db_index=True)),
                ('published_datetime', models.DateTimeField(db_index=True)),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
