version: '3.9'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build:
       context: .
    restart: always
    command: celery -A flagright_project worker --loglevel=info
    depends_on:
      - web
      - redis
  celery-beat:
    build:
       context: .
    restart: always
    command: celery -A flagright_project beat --loglevel=info
    depends_on:
      - web
      - redis
  